addons:
  sonarcloud:
    organization: "berkdulger-github"
    token:
      secure: $SECRET_KEY

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner